package:
  name: mpcmd
  version: 0.0.4

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:

  host:
    - python
    - pip

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - numba
    - gsd
    - memory_profiler
    - seaborn

test:
  imports:
    - mpcmd
  source_files:
    - tests
  commands:
    - python tests/test_import.py

about:
  summary: An simulation package.
  license_file: LICENSE
