package:
  name: mpcmd
  version: 0.0.4

source:
  url: https://files.pythonhosted.org/packages/6c/8f/11151dd66b27286d1be55a93592f70701696e4fb347ab388e6bb407ba7c8/mpcmd-0.0.4.tar.gz
  sha256: d6aefb5d98fff3420d8544bf5a383b0364d95028c2558c3df0019ac0cbaf44cb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:

  host:
    - python
    - pip

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - numba
    - gsd
    - memory_profiler
    - seaborn

test:
  imports:
    - mpcmd
  source_files:
    - tests
  commands:
    - python tests/test_import.py
    
about:
  home: https://github.com/dotmet/mpcmd
  summary: 'Extensible mpcd fluid simulation package'
  description: |
    An extensible fluid simulation package which combines multiple MPCD and md methods.
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". 
  # Optional
  license_family: MIT
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  doc_url: https://mpcmd.readthedocs.io/
  dev_url: https://github.com/dotmet/mpcmd

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - dotmet
